# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Mengjia Lyu and Machine Learning
  中文: 梦嘉和ML
email: mengjia.lyu@outlook.com
description:
  en: When ML meets ML
  中文: 当梦嘉遇见ML
index:
  en:
  中文: accueil.html
feed:
  en: /feed.xml
  中文: /flux.xml
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://mengjialyu.info" # the base hostname & protocol for your site
twitter_username: kayql131
github_username: YumekaMengjiaLYU

# Build settings
markdown: kramdown
