# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Mengjia Lyu and Machine Learning
  中文: 梦嘉和ML
email: mengjia.lyu@outlook.com
description:
  en: When ML meets ML|Love is always with you.
  中文: 当梦嘉遇见ML|爱，一直都在。
index:
  en:
  中文: accueil.html
feed:
  en: /feed.xml
  中文: /flux.xml
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://mengjialyu.info" # the base hostname & protocol for your site

github_username: YumekaMengjiaLYU
linkedin: user-name-mengjialyu
# Build settings
markdown: kramdown

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: mengjialyu
